<?php

namespace Database\Seeders;

use App\Models\JenisMotor;
use App\Models\Motor;
use Illuminate\Database\Seeder;

class MotorSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'jenis' => ['merk' => 'Honda', 'tipe' => 'skuter'],
                'nama_motor' => 'Honda Vario 160 CBS',
                'harga_jual' => 27600000,
                'deskripsi_motor' => 'Skutik premium dengan tampilan sporty, mesin 160cc eSP+, dan fitur modern.',
                'warna' => 'Matte Black',
                'kapasitas_mesin' => '160cc',
                'tahun' => 2025,
                'foto1' => 'seed/motor/honda-vario-160.png',
                'foto2' => 'seed/motor/honda-pcx-160.jpg',
                'foto3' => 'seed/motor/honda-scoopy.jpg',
                'stok' => 8,
                'status' => Motor::STATUS_TERSEDIA,
            ],
            [
                'jenis' => ['merk' => 'Honda', 'tipe' => 'skuter'],
                'nama_motor' => 'Honda PCX 160 ABS',
                'harga_jual' => 36000000,
                'deskripsi_motor' => 'Skutik elegan dengan ABS, bagasi lega, dan kenyamanan premium.',
                'warna' => 'Majestic Matte Red',
                'kapasitas_mesin' => '160cc',
                'tahun' => 2025,
                'foto1' => 'seed/motor/honda-pcx-160.jpg',
                'foto2' => 'seed/motor/honda-vario-160.png',
                'foto3' => 'seed/motor/honda-scoopy.jpg',
                'stok' => 6,
                'status' => Motor::STATUS_TERSEDIA,
            ],
            [
                'jenis' => ['merk' => 'Honda', 'tipe' => 'skuter'],
                'nama_motor' => 'Honda BeAT Street',
                'harga_jual' => 19100000,
                'deskripsi_motor' => 'Skutik ringan untuk mobilitas harian dengan desain street style.',
                'warna' => 'Street Black',
                'kapasitas_mesin' => '110cc',
                'tahun' => 2025,
                'foto1' => 'seed/motor/honda-beat-street.png',
                'foto2' => 'seed/motor/honda-vario-160.png',
                'foto3' => 'seed/motor/honda-scoopy.jpg',
                'stok' => 12,
                'status' => Motor::STATUS_TERSEDIA,
            ],
            [
                'jenis' => ['merk' => 'Honda', 'tipe' => 'skuter'],
                'nama_motor' => 'Honda Scoopy Stylish',
                'harga_jual' => 22500000,
                'deskripsi_motor' => 'Skutik retro modern dengan desain compact dan fitur smart key.',
                'warna' => 'Stylish Brown',
                'kapasitas_mesin' => '110cc',
                'tahun' => 2025,
                'foto1' => 'seed/motor/honda-scoopy.jpg',
                'foto2' => 'seed/motor/honda-beat-street.png',
                'foto3' => 'seed/motor/honda-vario-160.png',
                'stok' => 10,
                'status' => Motor::STATUS_TERSEDIA,
            ],
            [
                'jenis' => ['merk' => 'Yamaha', 'tipe' => 'sport_bike'],
                'nama_motor' => 'Yamaha R15 Connected',
                'harga_jual' => 39800000,
                'deskripsi_motor' => 'Motor sport fairing dengan DNA R-Series dan konektivitas modern.',
                'warna' => 'Icon Blue',
                'kapasitas_mesin' => '155cc',
                'tahun' => 2025,
                'foto1' => 'seed/motor/yamaha-r15.jpg',
                'foto2' => 'seed/motor/yamaha-nmax.jpg',
                'foto3' => 'seed/motor/kawasaki-ninja-250.jpg',
                'stok' => 4,
                'status' => Motor::STATUS_TERSEDIA,
            ],
            [
                'jenis' => ['merk' => 'Yamaha', 'tipe' => 'skuter'],
                'nama_motor' => 'Yamaha NMAX 155',
                'harga_jual' => 32600000,
                'deskripsi_motor' => 'Skuter maxi dengan posisi berkendara nyaman dan fitur konektivitas.',
                'warna' => 'Prestige Silver',
                'kapasitas_mesin' => '155cc',
                'tahun' => 2025,
                'foto1' => 'seed/motor/yamaha-nmax.jpg',
                'foto2' => 'seed/motor/yamaha-r15.jpg',
                'foto3' => 'seed/motor/honda-pcx-160.jpg',
                'stok' => 7,
                'status' => Motor::STATUS_TERSEDIA,
            ],
            [
                'jenis' => ['merk' => 'Yamaha', 'tipe' => 'skuter'],
                'nama_motor' => 'Yamaha Aerox 155',
                'harga_jual' => 29200000,
                'deskripsi_motor' => 'Skuter sporty bertenaga 155cc dengan karakter lincah untuk kota.',
                'warna' => 'CyberCity',
                'kapasitas_mesin' => '155cc',
                'tahun' => 2025,
                'foto1' => 'seed/motor/yamaha-nmax.jpg',
                'foto2' => 'seed/motor/yamaha-r15.jpg',
                'foto3' => 'seed/motor/honda-vario-160.png',
                'stok' => 9,
                'status' => Motor::STATUS_TERSEDIA,
            ],
            [
                'jenis' => ['merk' => 'Suzuki', 'tipe' => 'bebek'],
                'nama_motor' => 'Suzuki Smash FI',
                'harga_jual' => 19400000,
                'deskripsi_motor' => 'Motor bebek ekonomis dengan konsumsi bahan bakar irit.',
                'warna' => 'Titan Black',
                'kapasitas_mesin' => '115cc',
                'tahun' => 2024,
                'foto1' => 'seed/motor/suzuki-smash-fi.jpg',
                'foto2' => 'seed/motor/suzuki-address-fi.jpg',
                'foto3' => 'seed/motor/suzuki-satria-f150.jpg',
                'stok' => 5,
                'status' => Motor::STATUS_TERSEDIA,
            ],
            [
                'jenis' => ['merk' => 'Suzuki', 'tipe' => 'bebek'],
                'nama_motor' => 'Suzuki Satria F150',
                'harga_jual' => 29400000,
                'deskripsi_motor' => 'Motor underbone sporty dengan mesin 150cc dan tampilan agresif.',
                'warna' => 'Metallic Triton Blue',
                'kapasitas_mesin' => '150cc',
                'tahun' => 2025,
                'foto1' => 'seed/motor/suzuki-satria-f150.jpg',
                'foto2' => 'seed/motor/suzuki-smash-fi.jpg',
                'foto3' => 'seed/motor/suzuki-address-fi.jpg',
                'stok' => 6,
                'status' => Motor::STATUS_TERSEDIA,
            ],
            [
                'jenis' => ['merk' => 'Suzuki', 'tipe' => 'skuter'],
                'nama_motor' => 'Suzuki Address FI',
                'harga_jual' => 20100000,
                'deskripsi_motor' => 'Skuter praktis dengan bagasi luas dan konsumsi bahan bakar efisien.',
                'warna' => 'Brilliant White',
                'kapasitas_mesin' => '113cc',
                'tahun' => 2024,
                'foto1' => 'seed/motor/suzuki-address-fi.jpg',
                'foto2' => 'seed/motor/suzuki-smash-fi.jpg',
                'foto3' => 'seed/motor/honda-beat-street.png',
                'stok' => 7,
                'status' => Motor::STATUS_TERSEDIA,
            ],
            [
                'jenis' => ['merk' => 'Kawasaki', 'tipe' => 'dual_sport'],
                'nama_motor' => 'Kawasaki KLX 150',
                'harga_jual' => 33800000,
                'deskripsi_motor' => 'Dual purpose ringan untuk area kota dan off-road ringan.',
                'warna' => 'Lime Green',
                'kapasitas_mesin' => '150cc',
                'tahun' => 2025,
                'foto1' => 'seed/motor/kawasaki-klx-150.jpg',
                'foto2' => 'seed/motor/kawasaki-w175.jpg',
                'foto3' => 'seed/motor/kawasaki-ninja-250.jpg',
                'stok' => 3,
                'status' => Motor::STATUS_TERSEDIA,
            ],
            [
                'jenis' => ['merk' => 'Kawasaki', 'tipe' => 'sport_bike'],
                'nama_motor' => 'Kawasaki Ninja 250',
                'harga_jual' => 66500000,
                'deskripsi_motor' => 'Sport bike fairing 250cc untuk pengendara yang mengejar performa.',
                'warna' => 'Lime Green Ebony',
                'kapasitas_mesin' => '250cc',
                'tahun' => 2025,
                'foto1' => 'seed/motor/kawasaki-ninja-250.jpg',
                'foto2' => 'seed/motor/kawasaki-klx-150.jpg',
                'foto3' => 'seed/motor/yamaha-r15.jpg',
                'stok' => 2,
                'status' => Motor::STATUS_TERSEDIA,
            ],
            [
                'jenis' => ['merk' => 'Kawasaki', 'tipe' => 'retro'],
                'nama_motor' => 'Kawasaki W175 SE',
                'harga_jual' => 35200000,
                'deskripsi_motor' => 'Motor retro klasik dengan desain sederhana dan mesin mudah dirawat.',
                'warna' => 'Metallic Spark Black',
                'kapasitas_mesin' => '177cc',
                'tahun' => 2025,
                'foto1' => 'seed/motor/kawasaki-w175.jpg',
                'foto2' => 'seed/motor/kawasaki-klx-150.jpg',
                'foto3' => 'seed/motor/kawasaki-ninja-250.jpg',
                'stok' => 4,
                'status' => Motor::STATUS_TERSEDIA,
            ],
        ];

        foreach ($items as $item) {
            $jenis = JenisMotor::query()
                ->where('merk', $item['jenis']['merk'])
                ->where('tipe', $item['jenis']['tipe'])
                ->firstOrFail();

            unset($item['jenis']);

            Motor::updateOrCreate(
                ['nama_motor' => $item['nama_motor']],
                array_merge($item, ['jenis_motor_id' => $jenis->id]),
            );
        }
    }
}
